### PR TITLE
Widen API to allow storing keychain entries for an authenticated user

### PR DESCRIPTION
**Pull request by purejava**
Belongs to https://github.com/cryptomator/cryptomator/pull/3311

### CODE REVIEW

**Comment by infeo** [comment]
@purejava I released [integrations-api:1.4.0-beta3](https://github.com/cryptomator/integrations-api/releases/tag/1.4.0-beta3). Can you update your branch, such that we can run it on the CI?

**Comment by purejava** [comment]
@infeo Sure. Done.

**Review by tobihagemann — APPROVED** [review]
Looking good! To be honest, I just did some reformattings and refactorings to keep the diff small. I'm not sure if I've introduced any bugs. Please re-test before merging. :wink:

**Comment by infeo** [comment]
> Please re-test before merging

@purejava Do you want to do the honor?

**Comment by purejava** [comment]
> Looking good! To be honest, I just did some reformattings and refactorings to keep the diff small. I'm not sure if I've introduced any bugs. Please re-test before merging. 😉

Thanks for the overhaul @tobihagemann. I made a review reading the refactorings and tested the new commits. LGTM!

**Comment by purejava** [comment]
> > Please re-test before merging
> 
> @purejava Do you want to do the honor?

😄 Definitely! Done. LGTM.

**Pull request merged**
